### ISSUE TITLE
Diamond includes?

### ISSUE THREAD

**Issue by Boscop** [turnage/glslwatch#1]
How does it deal with diamond imports, does it deduplicate them, to keep the earliest instance?

**Comment by turnage** [comment]
Do you mean an import where src imports a, src imports b, and both a and b import c?

```
 src
 /  \
a   b
 \  /
   c
```
In this case c is just read from disk twice, not duplicated.

**Comment by Boscop** [comment]
Yes, like that. 
Let's say the import of `a` comes first, before the import of `b`. Will `c` be inlined into src only for `a`'s import?
(So that it won't lead to duplicate symbols.)

**Comment by turnage** [comment]
Well, now it will just substitute in the first inclusion, and ignore the rest.
